/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.room.booking.system;


import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author jackf
 */
public class EditBooking extends javax.swing.JFrame {

    /**
     * Creates new form EditBooking
     */
    public EditBooking() {  
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
       public final static Runnable runnable =
     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.exclamation"); // error sound

    public static void errorMesg(String mesg,String title){
        runnable.run(); 
        JOptionPane.showMessageDialog(null, mesg, title, JOptionPane.INFORMATION_MESSAGE);
    }
  
    public static final String regex = "^(.+)@(.+)$";

   public static boolean isValidEmail(String email) {
       EmailValidator validator = EmailValidator.getInstance();
       return validator.isValid(email);
   }

   public static void email(String[]args){
       List<String> emails = new ArrayList<String>();
       //Valid Email
       emails.add("jf@gmail.com");
       emails.add("jackfeng.#@gmail.com");
       emails.add("jackfeng#@gmail.com");
       //Invalid Email
       emails.add("#@example.com");
       emails.add("jfexample.com");
       emails.add("jf.example.com");

       Pattern pattern = Pattern.compile(regex);
       for (String value : emails){
           Matcher matcher = pattern.matcher(value);
       }
   }
          
       void setData() throws IOException {
            String tempFile = "Temp.txt";
        String currentLine;
        String data[];
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");

        int Room = Integer.parseInt(jRoomIDField.getText());
        String Floor = String.valueOf(jComboFloor.getSelectedItem());
        String InDay = date.format(jCheckInDate.getDate());
        String OutDay = date.format(jCheckOutDate.getDate());
        String CN = jCustomerNameField.getText();
        String ICP = jIC_PassportField.getText();
        String CC = jContactNoField.getText();
        String CEM = jEmailField.getText();
        
        try
        {
            FileWriter fw = new FileWriter(tempFile,true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            FileReader fr = new FileReader("addbooking.txt");
            BufferedReader br =new BufferedReader(fr);
            
            while ((currentLine = br.readLine()) != null) {
                data = currentLine.split(",");
       
                if (!data[0].equals("" + Room)) {
                    pw.println(currentLine);
                } else {
                    pw.println (Room +"," + Floor +","+ InDay +","+ OutDay
                        +"," + CN +"," + ICP +","+ CC +"," + CEM +",");
                  
                }
            }
         
            pw.flush();
            fr.close();
            br.close();
            fw.close();
            pw.close();
            bw.close();

        }
        catch (FileNotFoundException ex) {
            EditBooking.errorMesg("Error Occurred", "Title");

        }   catch (IOException ex) {
            java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        File oldFile = new File ("addbooking.txt");
        File newFile = new File (tempFile);
        System.out.println(oldFile.exists());
        if (oldFile.delete()) {
            System.out.println("Deleted the file: " + oldFile.getName());
        } else {
            System.out.println("Failed to delete the file.");
        }

        newFile.renameTo(new File("addBooking.txt"));

       }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jEditButton = new javax.swing.JButton();
        jResetButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jRoomIDField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jIC_PassportField = new javax.swing.JTextField();
        jCustomerNameField = new javax.swing.JTextField();
        jComboFloor = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jEmailField = new javax.swing.JTextField();
        jContactNoField = new javax.swing.JTextField();
        jBackButton = new javax.swing.JButton();
        jCheckOutDate = new com.toedter.calendar.JDateChooser();
        jCheckInDate = new com.toedter.calendar.JDateChooser();
        jEmailLabell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(228, 241, 254));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Booking");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel7.setBackground(new java.awt.Color(103, 128, 159));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Room ID:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Floor:");

        jEditButton.setBackground(new java.awt.Color(232, 232, 232));
        jEditButton.setText("Edit");
        jEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditButtonActionPerformed(evt);
            }
        });

        jResetButton.setBackground(new java.awt.Color(232, 232, 232));
        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Check-Out Date:");

        jRoomIDField.setEditable(false);
        jRoomIDField.setBackground(new java.awt.Color(232, 232, 232));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("Check-In Date:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel27.setText("Customer Name:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel28.setText("IC/Passport:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel29.setText("Contact No:");

        jIC_PassportField.setBackground(new java.awt.Color(232, 232, 232));

        jCustomerNameField.setBackground(new java.awt.Color(232, 232, 232));

        jComboFloor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Floor", "Floor 1", "Floor 2" }));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel30.setText("Email:");

        jEmailField.setBackground(new java.awt.Color(232, 232, 232));
        jEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmailFieldKeyPressed(evt);
            }
        });

        jContactNoField.setBackground(new java.awt.Color(232, 232, 232));

        jBackButton.setBackground(new java.awt.Color(232, 232, 232));
        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jCheckOutDate.setBackground(new java.awt.Color(103, 128, 159));

        jCheckInDate.setBackground(new java.awt.Color(103, 128, 159));
        jCheckInDate.setForeground(new java.awt.Color(232, 232, 232));

        jEmailLabell.setForeground(new java.awt.Color(252, 3, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29)
                    .addComponent(jLabel21)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmailLabell)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRoomIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jIC_PassportField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jCustomerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jComboFloor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jRoomIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jCustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jIC_PassportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmailLabell)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBackButton)
                    .addComponent(jResetButton)
                    .addComponent(jEditButton))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        ManageBooking rgf = new ManageBooking();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        
        jComboFloor.setSelectedItem("Choose a Floor");
        jCheckInDate.setDate(null);
        jCheckOutDate.setDate(null);
        jCustomerNameField.setText(null);
        jIC_PassportField.setText(null);
        jContactNoField.setText(null);
        jEmailField.setText(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButtonActionPerformed
            
        if("Choose a Floor".equals(jComboFloor.getSelectedItem())){
            JOptionPane.showMessageDialog(null,"Please Choose A Floor!");
            
            return;
        }
        
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(jEmailField.getText());
    
        try {
            if(matcher.matches()&&!"".equals(jRoomIDField.getText()) && !"".equals(jComboFloor.getSelectedItem()) && !"".equals(jCheckInDate.getDate()) && jCheckInDate.getDate()!=null &&
               !"".equals(jCheckOutDate.getDate())&& jCheckOutDate.getDate()!=null && !"".equals(jCustomerNameField.getText()) &&  !"".equals(jIC_PassportField.getText()) && 
               !"".equals( jContactNoField.getText()) &&  !"".equals(jEmailField.getText())){
            setData();
             JOptionPane.showMessageDialog(this,"Booking Edited Successfully");
              jRoomIDField.setText(null);
              jComboFloor.setSelectedItem("Choose a Floor");
              jCheckInDate.setDate(null);
              jCheckOutDate.setDate(null);
              jCustomerNameField.setText(null);
              jIC_PassportField.setText(null);  
              jContactNoField.setText(null);
              jEmailField.setText(null);
           }
        else{
             JOptionPane.showMessageDialog(this,"Please check the fields and the inputs!");   
                }
        } catch (IOException ex) {
            Logger.getLogger(EditBooking.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jEditButtonActionPerformed

    private void jEmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailFieldKeyPressed
       Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(jEmailField.getText());

        if(!matcher.matches()){
               jEmailLabell.setText("Wrong/Invalid Email Format");
         
        }else{
            jEmailLabell.setText(null);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jEmailFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    public com.toedter.calendar.JDateChooser jCheckInDate;
    public com.toedter.calendar.JDateChooser jCheckOutDate;
    public javax.swing.JComboBox<String> jComboFloor;
    public javax.swing.JTextField jContactNoField;
    public javax.swing.JTextField jCustomerNameField;
    private javax.swing.JButton jEditButton;
    public javax.swing.JTextField jEmailField;
    private javax.swing.JLabel jEmailLabell;
    public javax.swing.JTextField jIC_PassportField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jResetButton;
    public javax.swing.JTextField jRoomIDField;
    // End of variables declaration//GEN-END:variables
}
