/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.room.booking.system;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jackf
 */
public class ManageBooking extends javax.swing.JFrame {

   
    /**
     * Creates new form ManageBooking
     */
    public ManageBooking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public final static Runnable runnable =
     (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.exclamation"); // error sound

    public static void errorMesg(String mesg,String title){
        runnable.run(); 
        JOptionPane.showMessageDialog(null, mesg, title, JOptionPane.INFORMATION_MESSAGE);
    }
   
        String roomID;
        String floor;
        String checkindate;
        String checkoutdate;
        String customername;
        String ic_passport;
        String contactno;
        String email;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jDeleteButton = new javax.swing.JButton();
        jEditButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSearchField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jSignOutButton = new javax.swing.JButton();
        jDisplayButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Floor", "Check-In Date", "Check-Out Date", "Customer Name", "IC/Passport", "Contact No", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(80);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(1).setMinWidth(90);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(2).setMinWidth(90);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jDeleteButton.setBackground(new java.awt.Color(232, 232, 232));
        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jEditButton.setBackground(new java.awt.Color(232, 232, 232));
        jEditButton.setText("Edit");
        jEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditButtonActionPerformed(evt);
            }
        });

        jAddButton.setBackground(new java.awt.Color(232, 232, 232));
        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Booking");

        jSearchButton.setText("Search Here");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jSignOutButton.setText("Sign Out");
        jSignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignOutButtonActionPerformed(evt);
            }
        });

        jDisplayButton.setBackground(new java.awt.Color(232, 232, 232));
        jDisplayButton.setText("Display");
        jDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(355, 355, 355)
                        .addComponent(jSignOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSignOutButton)
                            .addComponent(jLabel1))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearchButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jDeleteButton)
                                .addComponent(jEditButton)
                                .addComponent(jAddButton)
                                .addComponent(jDisplayButton)))))
                .addContainerGap())
        );

        jMenu1.setText("Manage ");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Receipt");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
     
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                 
                if(jTable1.getSelectedRowCount()==1){
                    String RoomIDTable = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(),0));

                    String tempFile = "Temp.txt";
                    String currentLine;
                    String data[];
                try
                {
                    FileWriter fw = new FileWriter(tempFile,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    FileReader fr = new FileReader("addbooking.txt");
                    BufferedReader br =new BufferedReader(fr);
                    
                    while((currentLine = br.readLine())!= null)
                    
                    {
                    data = currentLine.split(",");
                    if(!(data[0].equalsIgnoreCase(RoomIDTable)))
                   
                    {
                        pw.println(currentLine);
                    }
                    }
                    pw.flush();
                    fr.close();
                    br.close();
                    fw.close();
                    pw.close();
                    bw.close();
   
                }
                catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Error Occurred");
                
                 }   catch (IOException ex) {
                        java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                     }
                     File oldFile = new File ("addbooking.txt");
                     File newFile = new File (tempFile);
                     System.out.println(oldFile.exists());
                         if (oldFile.delete()) { 
                                System.out.println("Deleted the file: " + oldFile.getName());
                        } else {
                                System.out.println("Failed to delete the file.");
                        }
                    
                        newFile.renameTo(new File("addBooking.txt"));
            }
                        model.setRowCount(0);
                   try{
                        File Flist = new File("addBooking.txt");
                        Scanner sc1 = new Scanner(Flist);
                        while(sc1.hasNextLine()){
                            String Line = sc1.nextLine();
                        if(!(Line.isEmpty())){
                         String[] wordsinLine = Line.split(",");
                         model.addRow(wordsinLine);
                     }
                   }
                         sc1.close();
                }        catch (FileNotFoundException ex) {
                         JOptionPane.showMessageDialog(null, "Error Occurred");
              }                    
                                            
// TODO add your handling code here:
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        AddBooking rgf = new AddBooking();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
         if (jSearchField.getText().equals("")){
            ManageBooking.errorMesg("Please Enter A Value!", "Error");
            return;
            }
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String search = jSearchField.getText();
        model.setRowCount(0);
        try{
            File Flist = new File("addbooking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains(search)){
                    String[] wordsinLine = Line.split(",");
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }

          jSearchField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jSignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignOutButtonActionPerformed
        LoginForm rgf = new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();                    // TODO add your handling code here:
    }//GEN-LAST:event_jSignOutButtonActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        Receipt rgf = new Receipt();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButtonActionPerformed
 
        EditBooking rgf = new EditBooking();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
       
       
        
      Date checkin = null;
        try {
            checkin = new SimpleDateFormat("dd-MM-yyyy").parse(checkindate);
        } catch (ParseException ex) {
            Logger.getLogger(ManageBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       Date checkout = null;
        try {
            checkout = new SimpleDateFormat("dd-MM-yyyy").parse(checkoutdate);
        } catch (ParseException ex) {
            Logger.getLogger(ManageBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
        rgf.jRoomIDField.setText(roomID);
        rgf.jComboFloor.setSelectedItem(floor);
        rgf.jCheckInDate.setDate(checkin);
        rgf.jCheckOutDate.setDate(checkout);
        rgf.jCustomerNameField.setText(customername);
        rgf.jIC_PassportField.setText(ic_passport);
        rgf.jContactNoField.setText(contactno);
        rgf.jEmailField.setText(email);

        
        
        
        
                
               // TODO add your handling code here:
    }//GEN-LAST:event_jEditButtonActionPerformed

    private void jDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayButtonActionPerformed
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
        try{
            File Flist = new File("addbooking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(",");
                    model.addRow(wordsinLine);
                }
            }
            sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jDisplayButtonActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        
        int selectedRow;
               
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                selectedRow = jTable1.getSelectedRow();

              
                roomID = model.getValueAt(selectedRow, 0).toString();
                floor = model.getValueAt(selectedRow, 1).toString();
                checkindate = model.getValueAt(selectedRow, 2).toString(); 
                checkoutdate = model.getValueAt(selectedRow, 3).toString();
                customername = model.getValueAt(selectedRow, 4).toString();
                ic_passport = model.getValueAt(selectedRow, 5).toString();
                contactno = model.getValueAt(selectedRow, 6).toString();
                email = model.getValueAt(selectedRow, 7).toString(); 
               
                  // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jDisplayButton;
    private javax.swing.JButton jEditButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JButton jSignOutButton;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
